package com.rink.model;

import java.util.HashMap;
import java.util.List;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class CountryDirectory {

	private HashMap<String, Country> country_map = new HashMap<>();
	
	public CountryDirectory(String response) {
		List<Country> country_list = parseResponseToList(response); //Turns the response string to a list of country objects
		if (country_list != null) { createHashMap(country_list);} //Maps the country objects to a hashmap for easy search
	}

	
	// Turns each element in the JSON response into a country object and adds that object to a List
	private List<Country> parseResponseToList(String response) {
		try {

			ObjectMapper objectMapper = new ObjectMapper();
			List<Country> countries = objectMapper.readValue(response, new TypeReference<List<Country>>() {
			});
			
			return countries;
			
		} catch (JsonMappingException e) {
			e.printStackTrace();
			return null;
		} catch (JsonProcessingException e) {
			e.printStackTrace();
			return null;
		}

	}
	//Takes the list of countries generated by Jackson and converts them to a HashMap which can be more easily searched
	private void createHashMap(List<Country> list) {
		for (Country c: list) {
			if (c.getCca3() == null) { continue;} //Skips the country if the CCA value is null
			
			country_map.put(c.getCca3().toUpperCase(), c);
		}			
	}
	
	//Looks up a country in the hashmap based on CCA code and returns if it exists
	public Country getCountryByCode(String code) {
		if (country_map.containsKey(code)) { return country_map.get(code);}
		
		return null;
	}
	
}
