package com.rink.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Collectors;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class CountryDirectory {

	//A hashmap containing each country object as a value with the CCA3 code as a key
	private HashMap<String, Country> country_map = new HashMap<>();
	
	//A list of the CCA3 code for each country that is "valid" meaning that it has at least one timezone and at least one spoken language
	private List<String> valid_country_codes; //A li
	
	public CountryDirectory(String response) {
		List<Country> country_list = parseResponseToList(response); //Turns the response string to a list of country objects
		if (country_list != null) { createHashMap(country_list);} //Maps the country objects to a hashmap for easy search
		
		this.valid_country_codes = country_map.entrySet().stream() //Creates a list of all entries in the country map to be filtered
				.filter(entry -> entry.getValue().getLanguages() != null) //Removes countries where there is not a languages attribute
				.filter(entry -> !entry.getValue().getLanguages().isEmpty()) //Removes countries where the language attribute is empty (no official languages)
				.filter(entry -> entry.getValue().getTimeZones() != null) //Removes countries where there is no timezone attribute
				.filter(entry -> !entry.getValue().getTimeZones().isEmpty()) //Removes countries where the timezones attribute is empty
				.map(Map.Entry::getKey).collect(Collectors.toList()); //Extracts the key from each passing entry and adds it to the list
	}

	
	// Turns each element in the JSON response into a country object and adds that object to a List
	private List<Country> parseResponseToList(String response) {
		try {

			ObjectMapper objectMapper = new ObjectMapper();
			List<Country> countries = objectMapper.readValue(response, new TypeReference<List<Country>>() {
			});
			
			return countries;
			
		} catch (JsonMappingException e) {
			e.printStackTrace();
			return null;
		} catch (JsonProcessingException e) {
			e.printStackTrace();
			return null;
		}
	}
	//Takes the list of countries generated by Jackson and converts them to a HashMap which can be more easily searched
	private void createHashMap(List<Country> list) {
		for (Country c: list) {
			if (c.getCca3() == null) { continue;} //Skips the country if the CCA value is null
			
			country_map.put(c.getCca3().toUpperCase(), c);
		}			
	}
	
	//Looks up a country in the hashmap based on CCA code and returns if it exists
	public Country getCountryByCode(String code) {
		if (country_map.containsKey(code)) { return country_map.get(code);}
		
		return null;
	}
	
	//Returns the list of all coutry codes
	public Set<String> getCountryCodes() {
		return this.country_map.keySet();
	}
	
	//Returns the list of all country codes with timezones and languages in the list
	public List<String> getValidCountryCodes() {
		return valid_country_codes;
	}
	
}